config/routes.rb
Rails.application.routes.draw do

  get 'rooms/show'

  devise_for :users
  root 'top#index'
  resources :sentences, only: %i(new create index destroy show edit update) do
    resources :reactions, only: %i(destroy create)
  end


  resources :users, only: %i(show) do
    resources :reactions, only:%i(index)
  end
  resources :chat, only: %i(create show)
  resources :matching, only: %i(index)

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat_message.rb
class ChatMessage < ApplicationRecord
    belongs_to :chat_room
    belongs_to :user
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
    has_many :chat_messages
    has_many :chat_room_users
end

app/models/chat_room_user.rb
class ChatRoomUser < ApplicationRecord
    belongs_to :chat_room
    belongs_to :user
end

app/models/jobs/application_job.rb
class ApplicationJob < ActiveJob::Base
end

app/models/reaction.rb
class Reaction < ApplicationRecord
  belongs_to :sentence, class_name: "Sentence"
  belongs_to :user, class_name: "User"
end

app/models/sentence.rb
class Sentence < ApplicationRecord
  #Timeline Start
  #アソシエーション(1:多)
  belongs_to :user
  has_many :reactions
  #Timeline End
  validates :title, presence: true
  validates :body, presence: true
  validates :author, presence: true
  validates :publisher, presence: true



end

app/models/user.rb
class User < ApplicationRecord
  #Timeline Start
  #アソシエーション(1:多)
  has_many :sentences
  has_many :reactions,dependent: :destroy
  has_many :reacted_sentences, through: :reactions, source: :sentence
  has_many :chat_messages
  has_many :chat_room_users

  validates :name, presence: true
  validates :email, presence: true
  validates :encrypted_password, presence: true

  def already_reacted?(sentence)
    self.reactions.exists?(sentence_id: sentence.id)
  end


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i(name self_introduction  bookmeter_id age job sex))
    devise_parameter_sanitizer.permit(:account_update, keys: %i(name self_introduction bookmeter_id age job sex))
  end

  def after_sign_in_path_for(resource)
    sentences_path
  end

end

app/controllers/chat_controller.rb
class ChatController < ApplicationController
  def create
    # 自分の持っているチャットルームを取得
    current_user_chat_rooms = ChatRoomUser.where(user_id: current_user.id).map(&:chat_room)
    # 自分の持っているチャットルームからチャット相手のいるルームを探す
    chat_room = ChatRoomUser.where(chat_room: current_user_chat_rooms, user_id: params[:user_id]).map(&:chat_room).first
    # なければ作成する
    if chat_room.blank?
      # chat_roomsテーブルにレコードを作成
      chat_room = ChatRoom.create
      ChatRoomUser.create(chat_room: chat_room, user_id: current_user.id)
      ChatRoomUser.create(chat_room: chat_room, user_id: params[:user_id])
    end
    # チャットルームへ遷移させる
    redirect_to action: :show, id: chat_room.id
  end
  
  def show
    # チャット相手の情報を取得する
    chat_room = ChatRoom.find_by(id: params[:id])
    @chat_room_user = chat_room.chat_room_users.
      where.not(user_id: current_user.id).first.user
    @chat_messages = ChatMessage.where(chat_room: chat_room).order(:created_at)
  end
end

app/controllers/matching_controller.rb
class MatchingController < ApplicationController
  def index
    got_reaction_user_ids = Reaction.where(sentence_id: Sentence.where(user_id: current_user.id).ids, like_id: 1).pluck(:user_id)
    match_sentences_from_currentuser = Reaction.where(user_id: current_user.id , sentence_id: Sentence.where(user_id: got_reaction_user_ids),like_id: 1).map(&:sentence_id)
    @match_users = User.where(id: Sentence.where(id: match_sentences_from_currentuser).map(&:user_id))
    @got_reaction_users_sentences = Sentence.where(user_id: current_user.id).map(&:id)
  end
end

app/controllers/reactions_controller.rb
class ReactionsController < ApplicationController

    before_action :authenticate_user!

    def create
        @reaction = current_user.reactions.create(sentence_id: params[:sentence_id],like_id: params[:like_id])
        redirect_back(fallback_location: sentences_path)
    end

    def index
      @sentences=Sentence.where(user_id:current_user.id)
      @reacted_sentences = current_user.reacted_sentences
      @liked_sentences = @reacted_sentences.where(like_id:1)
    end
end

app/controllers/sentences_controller.rb
class SentencesController < ApplicationController

    before_action :authenticate_user!

  def new
   @sentence = Sentence.new
  end

  def create
   @sentence = Sentence.new(sentence_params)
   @sentence.user = current_user
   if @sentence.save
     redirect_to :action => "index"
   else
     redirect_to :action => "new"
   end
  end


  def index
    @s=2
    @sentence = Sentence.find_by(id: @s)
    begin
        while @sentence.user_id == current_user.id || current_user.already_reacted?(@sentence) || @sentence.suspicious == true do
            @s = @s+1
            @sentence = Sentence.find_by(id: @s)
        end
    rescue NoMethodError
        @sentence= Sentence.find_by(id: 1)
    end
  end

  def destroy
    Sentence.find(params[:id]).destroy
    redirect_to :back
  end

  def show
    @sentence = Sentence.find_by(id: params[:id])
    @items = RakutenWebService::Ichiba::Item.search(:keyword => @sentence.title, :genre_id => "101931" ) # This returns Enamerable object
  end

  def edit
    @sentence = Sentence.find_by(id: params[:id])
  end

  def update
    @sentence = Sentence.find_by(id: params[:id])
    if @sentence.update(sentence_params)
      redirect_to action: "index"
    else
      redirect_to action: "edit"
    end
  end

    private
#セキュリティのため、許可した:bodyというデータだけ取ってくるようにする
  def sentence_params
    params.require(:sentence).permit(:body,:title,:author,:publisher,:page,:plus)
  end



end

app/controllers/top_controller.rb
class TopController < ApplicationController
  before_action :authenticate_user!
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
    
    def show
        @user = User.find_by(id: params[:id])
        
        got_reaction_user_ids = Reaction.where(sentence_id: Sentence.where(user_id: current_user.id).ids, like_id: 1).pluck(:user_id)
        match_sentences_from_currentuser = Reaction.where(user_id: current_user.id , sentence_id: Sentence.where(user_id: got_reaction_user_ids),like_id: 1).map(&:sentence_id)
        @match_users = User.where(id: Sentence.where(id: match_sentences_from_currentuser).map(&:user_id))
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chat_helper.rb
module ChatHelper
end

app/helpers/matching_helper.rb
module MatchingHelper
end

app/helpers/reactions_helper.rb
module ReactionsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sentences_helper.rb
module SentencesHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/sentences/edit.html.erb
<head>
  <style type="text/css">
    tablearea{
      width:100%;
      height:30%;
    }
  </style>
</head>

<%= form_for @sentence do |s| %>
    <div class="field">
        <%= s.label :編集画面 %>
        <br>
        タイトル
        <%= s.text_field :title,size:50 %>
        <br>
        何ページ?
        <%= s.number_field :page,size:50 %>
        <br>
        文章
        <br>
        <%= s.text_area :body,size:"100×100" %>
        <br>
        自由欄(他人に表示されません。)
        <br>
        <%= s.text_area :plus,size:"100×100" %>
        <br>
        出版社
        <%= s.text_field :publisher,size:50 %>
        <br>
        筆者
        <%= s.text_field :author,size:50 %>
        <br>
    </div>
    <div class="action">
        <%= s.submit %>
    </div>
<% end %>

app/views/sentences/index.html.erb
<div class="swipearea">
    <div class="sentence">
    <%=simple_format(@sentence.body) %>
    <% unless @sentence.id==1%>
      <div class="quote">
        <div class="quote-title">"<%= @sentence.title %>"</div>
        <div class="quote-others"> 著:<%= @sentence.author %><br>編集:<%= @sentence.publisher%>より</div>
      </div>
    <% end %>
    </div>
    <% unless @sentence.id==1 %>
        <div class="actions" id="actionBtnArea">
                <%=link_to sentence_reactions_path(@sentence, params: { sentence_id: params[:id]} , like_id: 2 ) , :method => :post do %>
                <i class="fas fa-times fa-4x color"></i>
                <% end %>
                <%=link_to sentence_reactions_path(@sentence, params: { sentence_id: params[:id]} , like_id: 1 ) , :method => :post do %>
                <i class="fas fa-heart fa-4x color"></i>
                <% end %>
        </div>
    <% else %>
        <div class="twitter">
            <a href="https://twitter.com/share?ref_src=twsrc%5Etfw" class="twitter-share-button" data-show-count="false">Tweet</a><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
        </div>
    <% end %>
</div>

app/views/sentences/new.html.erb
<%= form_for @sentence do |f| %>
 <div class="field">
   <%= f.label :タイトル %>
   <br>
   <%= f.text_field :title,size: 30 , placeholder:"メモをしたいタイトルを記入してください。"%>
   <br>
   <%= f.label :ページ %>
   <br>
   <%= f.number_field :page,size: 30 , placeholder:"メモをしたい一節のページ数を記入してください。"%>
   <br>
   <%= f.label :"一節" %>
   <br>
   <%= f.text_area :body,:size=>"45x10", maxlength: "120", rows: "5", class:"textarea-control" , placeholder:"お気に入りの一節を入力してください。"%>
   <br>
   <%= f.label :自由欄。他人に表示されません。 %>
   <br>
   <%= f.text_area :plus,:size=>"45x10", maxlength: "150", rows: "5", class:"textarea-control" , placeholder:"プライベートなメモをご記入ください。" %>
   <br>
   <%= f.label :出版社 %>
   <br>
   <%= f.text_field :publisher,size: 30, placeholder:"メモしたい本の出版社を記入してください。" %>
   <br>
   <%= f.label :筆者 %>
   <br>
   <%= f.text_field :author,size: 30, placeholder:"メモをしたい本の筆者を記入してください。" %>
   <br>
 </div>
 <div class="memo-submit">
   <%= f.submit"メモする", class: "btn submitBtn" %>
 </div>
<% end %>

app/views/sentences/show.html.erb
<p>楽天books</p>
<% @items.each do |item| %>
  <tr>
  <td><img src="<%= item['smallImageUrls'][0] %>"></td>
  <td><%= link_to item.name, "#{item.url}" %></td>
  <td align="right"><%= number_with_delimiter(item.price) %>円</td>
  <br>
  </tr>
<% end %>

app/views/users/show.html.erb
<% if current_user.id == @user.id %>
  <div class='userAction'>
      <div class="userAction_edit">
        <%= link_to edit_user_registration_path, :method => :get do %>
          <i class="fas fa-edit edit">編集</i>
        <% end %>
      </div>
      <div class="userAction_logout edit">
        <%= link_to destroy_user_session_path, :method => :delete do %>
          <i class="fas fa-edit edit">ログアウト</i>
        <% end %>
      </div>
  </div>
<% end %>


<div class='usershowPage'>
  <div class='user-show-container'>
    <div class='userInfo'>
      <div class='username'><p class="userInfop">名前:<%= @user.name %></p></div>
      <div class='userid'><p class="userInfop"><%= @user.id %>人目のユーザーです。</p></div>
      <div class='userInfo_selfIntroduction'><p class="userInfop">自己紹介:<%= @user.self_introduction %></p></div>
      <div class='bookmeter_id'>読書メーターURL:<%= @user.bookmeter_id %></div>
      <br>
      <% if @user.self_introduction.blank? %>
        <div class="userInfo_selfIntroduction"><p class="userInfop">自己紹介文は設定されていません。</p></div>
      <% end %>
      <% if @user.bookmeter_id.blank? %>
        <div class="bookmeter_id"><p class="userInfop">読書メーターURLは設定されていません。</p></div>
      <% end %>
    </div>
  </div>
</div>