config/routes.rb
Rails.application.routes.draw do

  get 'rooms/show'

  devise_for :users
  root 'top#index'
  resources :sentences, only: %i(new create index destroy show edit update) do
    resources :reactions, only: %i(destroy create)
  end


  resources :users, only: %i(show) do
    resources :reactions, only:%i(index)
  end
  resources :chat, only: %i(create show)
  resources :matching, only: %i(index)

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat_message.rb
class ChatMessage < ApplicationRecord
    belongs_to :chat_room
    belongs_to :user
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
    has_many :chat_messages
    has_many :chat_room_users
end

app/models/chat_room_user.rb
class ChatRoomUser < ApplicationRecord
    belongs_to :chat_room
    belongs_to :user
end

app/models/reaction.rb
class Reaction < ApplicationRecord
  belongs_to :sentence, class_name: "Sentence"
  belongs_to :user, class_name: "User"
end

app/models/sentence.rb
class Sentence < ApplicationRecord
  #Timeline Start
  #アソシエーション(1:多)
  belongs_to :user
  has_many :reactions
  #Timeline End
  validates :title, presence: true
  validates :body, presence: true
  validates :author, presence: true
  validates :publisher, presence: true



end

app/models/user.rb
class User < ApplicationRecord
  #Timeline Start
  #アソシエーション(1:多)
  has_many :sentences
  has_many :reactions,dependent: :destroy
  has_many :reacted_sentences, through: :reactions, source: :sentence
  has_many :chat_messages
  has_many :chat_room_users

  validates :name, presence: true
  validates :email, presence: true
  validates :encrypted_password, presence: true

  def already_reacted?(sentence)
    self.reactions.exists?(sentence_id: sentence.id)
  end


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i(name self_introduction  bookmeter_id age job sex))
    devise_parameter_sanitizer.permit(:account_update, keys: %i(name self_introduction bookmeter_id age job sex))
  end

  def after_sign_in_path_for(resource)
    sentences_path
  end

end

app/controllers/chat_controller.rb
class ChatController < ApplicationController
  def create
    # 自分の持っているチャットルームを取得
    current_user_chat_rooms = ChatRoomUser.where(user_id: current_user.id).map(&:chat_room)
    # 自分の持っているチャットルームからチャット相手のいるルームを探す
    chat_room = ChatRoomUser.where(chat_room: current_user_chat_rooms, user_id: params[:user_id]).map(&:chat_room).first
    # なければ作成する
    if chat_room.blank?
      # chat_roomsテーブルにレコードを作成
      chat_room = ChatRoom.create
      ChatRoomUser.create(chat_room: chat_room, user_id: current_user.id)
      ChatRoomUser.create(chat_room: chat_room, user_id: params[:user_id])
    end
    # チャットルームへ遷移させる
    redirect_to action: :show, id: chat_room.id
  end
  
  def show
    # チャット相手の情報を取得する
    chat_room = ChatRoom.find_by(id: params[:id])
    @chat_room_user = chat_room.chat_room_users.
      where.not(user_id: current_user.id).first.user
    @chat_messages = ChatMessage.where(chat_room: chat_room).order(:created_at)
  end
end

app/controllers/matching_controller.rb
class MatchingController < ApplicationController
  def index
    got_reaction_user_ids = Reaction.where(sentence_id: Sentence.where(user_id: current_user.id).ids, like_id: 1).pluck(:user_id)
    match_sentences_from_currentuser = Reaction.where(user_id: current_user.id , sentence_id: Sentence.where(user_id: got_reaction_user_ids),like_id: 1).map(&:sentence_id)
    @match_users = User.where(id: Sentence.where(id: match_sentences_from_currentuser).map(&:user_id))
    @got_reaction_users_sentences = Sentence.where(user_id: current_user.id).map(&:id)
  end
end

app/controllers/reactions_controller.rb
class ReactionsController < ApplicationController

    before_action :authenticate_user!

    def create
        @reaction = current_user.reactions.create(sentence_id: params[:sentence_id],like_id: params[:like_id])
        redirect_back(fallback_location: sentences_path)
    end

    def index
      @sentences=Sentence.where(user_id:current_user.id)
      @reacted_sentences = current_user.reacted_sentences
      @liked_sentences = @reacted_sentences.where(like_id:1)
    end
end

app/controllers/sentences_controller.rb
class SentencesController < ApplicationController

    before_action :authenticate_user!

  def new
   @sentence = Sentence.new
  end

  def create
   @sentence = Sentence.new(sentence_params)
   @sentence.user = current_user
   if @sentence.save
     redirect_to :action => "index"
   else
     redirect_to :action => "new"
   end
  end


  def index
    @s=2
    @sentence = Sentence.find_by(id: @s)
    begin
        while @sentence.user_id == current_user.id || current_user.already_reacted?(@sentence) || @sentence.suspicious == true do
            @s = @s+1
            @sentence = Sentence.find_by(id: @s)
        end
    rescue NoMethodError
        @sentence= Sentence.find_by(id: 1)
    end
  end

  def destroy
    Sentence.find(params[:id]).destroy
    redirect_to :back
  end

  def show
    @sentence = Sentence.find_by(id: params[:id])
    @items = RakutenWebService::Ichiba::Item.search(:keyword => @sentence.title, :genre_id => "101931" ) # This returns Enamerable object
  end

  def edit
    @sentence = Sentence.find_by(id: params[:id])
  end

  def update
    @sentence = Sentence.find_by(id: params[:id])
    if @sentence.update(sentence_params)
      redirect_to action: "index"
    else
      redirect_to action: "edit"
    end
  end

    private
#セキュリティのため、許可した:bodyというデータだけ取ってくるようにする
  def sentence_params
    params.require(:sentence).permit(:body,:title,:author,:publisher,:page,:plus)
  end



end

app/controllers/top_controller.rb
class TopController < ApplicationController
  before_action :authenticate_user!
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
    
    def show
        @user = User.find_by(id: params[:id])
        
        got_reaction_user_ids = Reaction.where(sentence_id: Sentence.where(user_id: current_user.id).ids, like_id: 1).pluck(:user_id)
        match_sentences_from_currentuser = Reaction.where(user_id: current_user.id , sentence_id: Sentence.where(user_id: got_reaction_user_ids),like_id: 1).map(&:sentence_id)
        @match_users = User.where(id: Sentence.where(id: match_sentences_from_currentuser).map(&:user_id))
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chat_helper.rb
module ChatHelper
end

app/helpers/matching_helper.rb
module MatchingHelper
end

app/helpers/reactions_helper.rb
module ReactionsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sentences_helper.rb
module SentencesHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chat/show.html.erb
<div class="chatPage">
  <header class="header">
  <%= link_to "", matching_index_path, class: "linkToMatching" %>
    <div class="chatPartner">

      <div class="chatPartner_name"><%= @chat_room_user.name %></div>
    </div>
  </header>
  <div class="chat-container">
    <div class="messagesArea messages">
      <%= render @chat_messages %>
    </div>
  </div>
  <form class="messageInputForm">
    <div class='chat-container'>
      <input type="text" data-behavior="room_speaker" class="messageInputForm_input" placeholder="メッセージを入力...">
    </div>
  </form>
</div>

app/views/matching/index.html.erb
<div class="match-container">
    <h2 class="matchercontainer">マッチング一覧</h2>
    <div class="matcherlist">
          <div class="match">
        <% @match_users.each do |user| %>
            <div class="matching-body">
              <div class="matchingPerson">
                  <div class="matchingPerson_name"><%= link_to user.name,user_path(user.id) %></div>
              </div>
              <div class="openchat">
                  <%= form_tag :chat_index, method: :post do %>
                      <input name="user_id" type="hidden" value="<%= user.id %>" />
                  <%= submit_tag 'チャットを開く', class: "chatForm_btn" %>
                  <% end %>
              </div>
              <p class="match-like">相手からのいいね。</p>
              <% match_sentences_to_currentuser = Reaction.where(sentence_id: @got_reaction_users_sentences , user_id: user.id).map(&:sentence_id) %>
              <% match_sentences_to_currentuser = Sentence.where(id: match_sentences_to_currentuser) %>
              <% match_sentences_to_currentuser.each do |sentence| %>
                <p class="match-title"><%= sentence.title %></p>
              <% end %>
              <p class="match-liked">自分からのいいね</p>
              <% match_sentences_from_currentuser = Reaction.where(user_id: current_user.id , sentence_id: Sentence.where(user_id: user.id),like_id: 1).map(&:sentence_id) %>
              <% match_sentences_from_currentuser = Sentence.where(id: match_sentences_from_currentuser) %>
              <% match_sentences_from_currentuser.each do |sentence| %>
                <p class="match-title"><%= sentence.title %></p>
              <% end %>
              </div>
        <% end %>
            </div>

      </div>
</div>

app/views/reactions/index.html.erb
<div class="post">
<%= link_to new_sentence_path, :method => :get do %>
  <i class="fas fa-edit memo">新しくメモする</i>
<% end %>
</div>
<br>


<div class=reaction-navi>
  <div class="posted">
    <p class="posted-navi">投稿したメモ</p>

      <% @sentences.each do |sentence| %>
        <div class="reac-container">
          <div class="title">
            <%= link_to sentence.title, sentence_path(sentence.id) %>
            (P.<%=sentence.page %>)
            <%= link_to "編集", edit_sentence_path(sentence.id) %>
          </div>
          <div class="sentencebox">
            <%=simple_format(sentence.body) %>
          </div>
          <div class="reac-sentences-subnavi">
            <div class="author">
              著者:<%=sentence.author %>
            </div>
            <div class="publisher">
              出版:<%=sentence.publisher %>
            </div>
            <div class="plus">
              プライベートメモ:<%=sentence.plus %>
            </div>
          </div>
        </div>
      <% end %>

    </div>

    <div class="liked">
      <p class="liked-navi">いいねしたメモ</p>

      <% @reacted_sentences.each do |sentence|%>
        <div class="reac-container">
          <div class="title">
            <%= link_to sentence.title, sentence_path(sentence.id) %>
            (P.<%= sentence.page %>)
          </div>
          <div class="sentencebox">
            <%=sentence.body %>
          </div>
          <div class="reac-sentences-subnavi">
            <div class="author">
              著者:<%=sentence.author %>
            </div>
            <div class="publisher">
              出版社:<%=sentence.publisher %>
            </div>
          </div>
        </div>
      <% end %>

    </div>

app/views/reactions/show.html.erb
<div class="post">
<%= link_to new_sentence_path, :method => :get do %>
  <i class="fas fa-edit memo">新しくメモする</i>
<% end %>
</div>
<br>


<div class=reaction-navi>
  <div class="posted">
    <p class="posted-navi">投稿したメモ</p>

      <% @sentences.each do |sentence| %>
        <div class="reac-container">
          <div class="title">
            <%= link_to sentence.title, sentence_path(sentence.id) %>
            (P.<%=sentence.page %>)
            <%= link_to "編集", edit_sentence_path(sentence.id) %>
          </div>
          <div class="sentencebox">
            <%=simple_format(sentence.body) %>
          </div>
          <div class="reac-sentences-subnavi">
            <div class="author">
              著者:<%=sentence.author %>
            </div>
            <div class="publisher">
              出版:<%=sentence.publisher %>
            </div>
            <div class="plus">
              プライベートメモ:<%=sentence.plus %>
            </div>
          </div>
        </div>
      <% end %>

    </div>

    <div class="liked">
      <p class="liked-navi">いいねしたメモ</p>

      <% @reacted_sentences.each do |sentence|%>
        <div class="reac-container">
          <div class="title">
            <%= link_to sentence.title, sentence_path(sentence.id) %>
            (P.<%= sentence.page %>)
          </div>
          <div class="sentencebox">
            <%=sentence.body %>
          </div>
          <div class="reac-sentences-subnavi">
            <div class="author">
              著者:<%=sentence.author %>
            </div>
            <div class="publisher">
              出版社:<%=sentence.publisher %>
            </div>
          </div>
        </div>
      <% end %>

    </div>

app/views/top/index.html.erb
<div class="titlelogo-container">
  <p class="titlelogo">みんなの読書メモ</p>
</div>

<p class="how-to-use-navi">使い方ガイド</p>

<div class="how-to-use-container-container">
  <div class="how-to-user-container"><p class="bottom-like">プロフィール</p><p class="how-to-use">マッチング相手に表示されるプロフィールを編集できます。</p></div>
  <div class="how-to-user-container"><p class="bottom-like">スワイプ</p><p class="how-to-use">他ユーザーのメモをスワイプできます。</p></div>
  <div class="how-to-user-container"><p class="bottom-like">メモ帳</p><p class="how-to-use">お気に入りの一節をメモ出来ます。いいねしたメモを確認できます。</p></div>
  <div class="how-to-user-container"><p class="bottom-like">チャット</p><p class="how-to-use">マッチングした相手とチャットが出来ます。</p></div>
</div>

<div class="guide-to-add-container">
  <div class="onegai">ホーム画面への追加をお願いします。</div>
  <div class="chrome">
  <div class="browser">chromeの場合</div>
  <div class="browser-how-to">画面右上の設定アイコンを押し、ホーム画面へ追加をタップ</div>
  </div>
  <div class="Safari">
  <div class="browser">safariの場合</div>
  <div class="browser-how-to">画面下部の共有アイコンを押し、ホーム画面へ追加をタップ</div>
  </div>
</div>

<div class="campaign-container">
  <div class="campaign-info">現在開催中の献本キャンペーン</div>
</div>