config/routes.rb
Rails.application.routes.draw do

  get 'rooms/show'

  devise_for :users
  root 'top#index'
  resources :sentences, only: %i(new create index destroy show edit update) do
    resources :reactions, only: %i(destroy create)
  end


  resources :users, only: %i(show) do
    resources :reactions, only:%i(index)
  end
  resources :chat, only: %i(create show)
  resources :matching, only: %i(index)

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat_message.rb
class ChatMessage < ApplicationRecord
    belongs_to :chat_room
    belongs_to :user
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
    has_many :chat_messages
    has_many :chat_room_users
end

app/models/chat_room_user.rb
class ChatRoomUser < ApplicationRecord
    belongs_to :chat_room
    belongs_to :user
end

app/models/reaction.rb
class Reaction < ApplicationRecord
  belongs_to :sentence, class_name: "Sentence"
  belongs_to :user, class_name: "User"
end

app/models/sentence.rb
class Sentence < ApplicationRecord
  #Timeline Start
  #アソシエーション(1:多)
  belongs_to :user
  has_many :reactions
  #Timeline End
  validates :title, presence: true
  validates :body, presence: true
  validates :author, presence: true
  validates :publisher, presence: true



end

app/models/user.rb
class User < ApplicationRecord
  #Timeline Start
  #アソシエーション(1:多)
  has_many :sentences
  has_many :reactions,dependent: :destroy
  has_many :reacted_sentences, through: :reactions, source: :sentence
  has_many :chat_messages
  has_many :chat_room_users

  validates :name, presence: true
  validates :email, presence: true
  validates :encrypted_password, presence: true

  def already_reacted?(sentence)
    self.reactions.exists?(sentence_id: sentence.id)
  end


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


end

app/controllers/chat_controller.rb
class ChatController < ApplicationController
  def create
    # 自分の持っているチャットルームを取得
    current_user_chat_rooms = ChatRoomUser.where(user_id: current_user.id).map(&:chat_room)
    # 自分の持っているチャットルームからチャット相手のいるルームを探す
    chat_room = ChatRoomUser.where(chat_room: current_user_chat_rooms, user_id: params[:user_id]).map(&:chat_room).first
    # なければ作成する
    if chat_room.blank?
      # chat_roomsテーブルにレコードを作成
      chat_room = ChatRoom.create
      ChatRoomUser.create(chat_room: chat_room, user_id: current_user.id)
      ChatRoomUser.create(chat_room: chat_room, user_id: params[:user_id])
    end
    # チャットルームへ遷移させる
    redirect_to action: :show, id: chat_room.id
  end
  
  def show
    # チャット相手の情報を取得する
    chat_room = ChatRoom.find_by(id: params[:id])
    @chat_room_user = chat_room.chat_room_users.
      where.not(user_id: current_user.id).first.user
    @chat_messages = ChatMessage.where(chat_room: chat_room).order(:created_at)
  end
end

app/controllers/matching_controller.rb
class MatchingController < ApplicationController
  def index
    got_reaction_user_ids = Reaction.where(sentence_id: Sentence.where(user_id: current_user.id).ids, like_id: 1).pluck(:user_id)
    match_sentences_from_currentuser = Reaction.where(user_id: current_user.id , sentence_id: Sentence.where(user_id: got_reaction_user_ids),like_id: 1).map(&:sentence_id)
    @match_users = User.where(id: Sentence.where(id: match_sentences_from_currentuser).map(&:user_id))
    @got_reaction_users_sentences = Sentence.where(user_id: current_user.id).map(&:id)
  end
end

app/controllers/reactions_controller.rb
class ReactionsController < ApplicationController

    before_action :authenticate_user!

    def create
        @reaction = current_user.reactions.create(sentence_id: params[:sentence_id],like_id: params[:like_id])
        redirect_back(fallback_location: sentences_path)
    end

    def index
      @sentences=Sentence.where(user_id:current_user.id)
      @reacted_sentences = current_user.reacted_sentences
      @liked_sentences = @reacted_sentences.where(like_id:1)
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  before_action :authenticate_user!
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
    
    def show
        @user = User.find_by(id: params[:id])
        
        got_reaction_user_ids = Reaction.where(sentence_id: Sentence.where(user_id: current_user.id).ids, like_id: 1).pluck(:user_id)
        match_sentences_from_currentuser = Reaction.where(user_id: current_user.id , sentence_id: Sentence.where(user_id: got_reaction_user_ids),like_id: 1).map(&:sentence_id)
        @match_users = User.where(id: Sentence.where(id: match_sentences_from_currentuser).map(&:user_id))
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chat_helper.rb
module ChatHelper
end

app/helpers/matching_helper.rb
module MatchingHelper
end

app/helpers/reactions_helper.rb
module ReactionsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sentences_helper.rb
module SentencesHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>みんなの読書メモ</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0 , minimum-scale=1.0">
    <meta name="current_user_id" content="<%= current_user.id if current_user %>">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="topPage">
  <nav class="nav">
    <ul>
      <li class="home">
        <%= link_to "ホーム", root_path , class: "button" %>
      </li>
      <li class="appIcon">
        <% if user_signed_in? %>
        <%= link_to "プロフィール", user_path(current_user.id), class: "button" , :method => :get %>
        <% end %>
      </li>
      <li class="swipe">
          <%= link_to "スワイプ", sentences_path , class: "button"%>
      </li>
      <li class="booksIcon">
        <% if user_signed_in? %>
        <%= link_to "メモ帳", user_reactions_path(current_user.id), class: "button", :method => :get  %>
        <% end %>
      </li>
      <li class="messageIcon">
        <% if user_signed_in? %>
        <%= link_to "マッチング"  , matching_index_path, class: "button", :method => :get  %>
        <% end %>
      </li>
    </ul>
  </nav>
  </div>

  <% if flash[:notice] %>
    <div class="alert alert-info"><%= flash[:notice] %></div>
  <% end %>
  <% if flash[:alert] %>
    <div class="alert alert-danger"><%= flash[:alert] %></div>
  <% end %>
    <%= yield %>
  </body>
</html>